### ISSUE TITLE
Add support for hamlib for rotor control

### ISSUE THREAD

**Issue by fab4space** [hazrmard/SatTrack#2]
In addition to servo motor, a nice feature would be to add also support for hamlib via TCP for rotor control (basic version can just send Position commands for alt/az):
http://manpages.ubuntu.com/manpages/xenial/man8/rotctld.8.html
This will allow to control all the rotors which are supported by hamlib!

**Comment by hazrmard** [comment]
Thanks for the suggestion. I am not familiar with `hamlib` but it sounds like a good feature to add. I cannot say when (or if) I'll be able to do anything, but you are most welcome to fork this and send in a pull request.  
`sattrack/sattrack.py` defines `ServoController` class which has 2 instances of `Motor` objects. The `SatTrack` class instantiates the controller and gets 2 motors from it (see _SatTrack.connect_servos()_). You can change the controller class with a TCP option which attaches similar motor objects to its instances but which use hamlib. You'd want to make sure that aside from their connection, the motor objects have the same signature (i.e. motor functions and attributes) so the main package's interface to the motors is unchanged. Cheers!

**Comment by fab4space** [comment]
Thanks for your proposition! Ok I don't know when exactly but I will try to add this feature based on your advice. Many thanks and congratulations for this awesome software!!
